/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.HospitalList;
import model.PersonList;

/**
 *
 * @author amretasrerengarajan
 */
public class CommuityPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommuityPanel
     */
    HospitalList hosList;
    PersonList prsnList;
    
    public CommuityPanel(HospitalList hospList, PersonList prsnList) {
        initComponents();
        this.hosList = hospList;
        this.prsnList = prsnList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        splitPane = new javax.swing.JSplitPane();
        optionsPanel = new javax.swing.JPanel();
        btnAddHospital = new javax.swing.JButton();
        btnSearchHospitals = new javax.swing.JButton();
        btnViewHospitals = new javax.swing.JButton();
        btnViewPerson = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 255, 204));

        lblTitle.setBackground(new java.awt.Color(0, 255, 204));
        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Community Portal");

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        optionsPanel.setBackground(new java.awt.Color(255, 0, 204));

        btnAddHospital.setBackground(new java.awt.Color(204, 255, 204));
        btnAddHospital.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnAddHospital.setForeground(new java.awt.Color(0, 204, 0));
        btnAddHospital.setText("Add Hospital");
        btnAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalActionPerformed(evt);
            }
        });

        btnSearchHospitals.setBackground(new java.awt.Color(204, 255, 204));
        btnSearchHospitals.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSearchHospitals.setForeground(new java.awt.Color(0, 204, 0));
        btnSearchHospitals.setText("Search Hospitals");
        btnSearchHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHospitalsActionPerformed(evt);
            }
        });

        btnViewHospitals.setBackground(new java.awt.Color(204, 255, 204));
        btnViewHospitals.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnViewHospitals.setForeground(new java.awt.Color(0, 204, 0));
        btnViewHospitals.setText("View Hospitals");
        btnViewHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalsActionPerformed(evt);
            }
        });

        btnViewPerson.setBackground(new java.awt.Color(204, 255, 204));
        btnViewPerson.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnViewPerson.setForeground(new java.awt.Color(0, 204, 102));
        btnViewPerson.setText("View Patients Home");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 102));
        jButton1.setText("Add Community Admin");

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAddHospital)
                .addGap(18, 18, 18)
                .addComponent(btnViewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnSearchHospitals)
                .addGap(52, 52, 52)
                .addComponent(btnViewHospitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddHospital, btnSearchHospitals, btnViewHospitals, btnViewPerson, jButton1});

        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHospital)
                    .addComponent(jButton1)
                    .addComponent(btnViewPerson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchHospitals)
                    .addComponent(btnViewHospitals))
                .addContainerGap())
        );

        splitPane.setTopComponent(optionsPanel);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splitPane)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(splitPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalActionPerformed
        // TODO add your handling code here:
        CommunityPortal commPanel = new CommunityPortal(hosList);
        splitPane.setBottomComponent(commPanel);
    }//GEN-LAST:event_btnAddHospitalActionPerformed

    private void btnSearchHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHospitalsActionPerformed
        // TODO add your handling code here:
        SearchHospitalPanel searchHospitals = new SearchHospitalPanel(hosList, "Community Login");
        splitPane.setBottomComponent(searchHospitals);
    }//GEN-LAST:event_btnSearchHospitalsActionPerformed

    private void btnViewHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalsActionPerformed
        // TODO add your handling code here:
        ViewHospitalPanel viewPanel = new ViewHospitalPanel(hosList);
        splitPane.setBottomComponent(viewPanel);
    }//GEN-LAST:event_btnViewHospitalsActionPerformed

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        // TODO add your handling code here:
        ViewPersonPanel viewPersonDetails = new ViewPersonPanel(prsnList);
        splitPane.setBottomComponent(viewPersonDetails);
    }//GEN-LAST:event_btnViewPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHospital;
    private javax.swing.JButton btnSearchHospitals;
    private javax.swing.JButton btnViewHospitals;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
