/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.HospitalList;
import model.PatientRecord;
import model.PatientRecordList;
import model.PersonList;

/**
 *
 * @author amretasrerengarajan
 */
public class SystemAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminPanel
     */
    PatientRecord patientRecord;
    PatientRecordList patientList;
    PersonList personList;
    HospitalList hospitalList;
    
    public SystemAdminPanel(PatientRecord patientRecord, PatientRecordList patientList, PersonList personList, HospitalList hospitalList) {
        
        this.patientRecord = patientRecord;
        this.patientList = patientList;
        this.personList = personList;
        this.hospitalList = hospitalList;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        splitPane = new javax.swing.JSplitPane();
        navigationPanel = new javax.swing.JPanel();
        btnAddPatient = new javax.swing.JButton();
        btnAddEncounter = new javax.swing.JButton();
        btnViewPatient = new javax.swing.JButton();
        btnViewEncounter = new javax.swing.JButton();
        btnAddHospitals = new javax.swing.JButton();
        btnSearchHospitals = new javax.swing.JButton();
        btnViewHospitals = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("System Admin Panel");

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navigationPanel.setBackground(new java.awt.Color(255, 0, 204));

        btnAddPatient.setBackground(new java.awt.Color(204, 255, 204));
        btnAddPatient.setForeground(new java.awt.Color(0, 204, 51));
        btnAddPatient.setText("Add Patient");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });

        btnAddEncounter.setBackground(new java.awt.Color(204, 255, 204));
        btnAddEncounter.setForeground(new java.awt.Color(0, 204, 51));
        btnAddEncounter.setText("Add Encounter");
        btnAddEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEncounterActionPerformed(evt);
            }
        });

        btnViewPatient.setBackground(new java.awt.Color(204, 255, 204));
        btnViewPatient.setForeground(new java.awt.Color(0, 204, 51));
        btnViewPatient.setText("View Patient");
        btnViewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPatientActionPerformed(evt);
            }
        });

        btnViewEncounter.setBackground(new java.awt.Color(204, 255, 204));
        btnViewEncounter.setForeground(new java.awt.Color(0, 204, 51));
        btnViewEncounter.setText("View Encounter");
        btnViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterActionPerformed(evt);
            }
        });

        btnAddHospitals.setBackground(new java.awt.Color(204, 255, 204));
        btnAddHospitals.setForeground(new java.awt.Color(0, 204, 51));
        btnAddHospitals.setText("Add Hospitals");
        btnAddHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospitalsActionPerformed(evt);
            }
        });

        btnSearchHospitals.setBackground(new java.awt.Color(204, 255, 204));
        btnSearchHospitals.setForeground(new java.awt.Color(0, 204, 51));
        btnSearchHospitals.setText("Search Hospitals");
        btnSearchHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHospitalsActionPerformed(evt);
            }
        });

        btnViewHospitals.setBackground(new java.awt.Color(204, 255, 204));
        btnViewHospitals.setForeground(new java.awt.Color(0, 204, 51));
        btnViewHospitals.setText("View Hospitals");
        btnViewHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHospitalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnAddEncounter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnViewEncounter)
                .addContainerGap())
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(btnAddHospitals)
                .addGap(18, 18, 18)
                .addComponent(btnSearchHospitals)
                .addGap(18, 18, 18)
                .addComponent(btnViewHospitals)
                .addGap(88, 88, 88))
        );

        navigationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddEncounter, btnAddPatient, btnViewEncounter, btnViewPatient});

        navigationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddHospitals, btnSearchHospitals, btnViewHospitals});

        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPatient)
                    .addComponent(btnAddEncounter)
                    .addComponent(btnViewPatient)
                    .addComponent(btnViewEncounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHospitals)
                    .addComponent(btnSearchHospitals)
                    .addComponent(btnViewHospitals))
                .addContainerGap())
        );

        splitPane.setTopComponent(navigationPanel);

        displayPanel.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(displayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splitPane)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(splitPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        AddPatientPanel addPatientPanel = new AddPatientPanel(patientList, personList);
        splitPane.setBottomComponent(addPatientPanel);
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void btnAddEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEncounterActionPerformed
        // TODO add your handling code here:
        AddPatientEncounter addPatientEncounterPanel = new AddPatientEncounter(patientList, patientRecord, personList);
        splitPane.setBottomComponent(addPatientEncounterPanel);
    }//GEN-LAST:event_btnAddEncounterActionPerformed

    private void btnViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPatientActionPerformed
        // TODO add your handling code here:
        ViewPersonPanel viewPersonPanel = new ViewPersonPanel(personList);
        splitPane.setBottomComponent(viewPersonPanel);
    }//GEN-LAST:event_btnViewPatientActionPerformed

    private void btnViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterActionPerformed
        // TODO add your handling code here:
        ViewPatientPanel viewPatientPanel = new ViewPatientPanel(patientList, patientRecord, personList);
        splitPane.setBottomComponent(viewPatientPanel);
    }//GEN-LAST:event_btnViewEncounterActionPerformed

    private void btnAddHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospitalsActionPerformed
        // TODO add your handling code here:
        CommunityPortal addHospitalsPanel = new CommunityPortal(hospitalList);
        splitPane.setBottomComponent(addHospitalsPanel);
    }//GEN-LAST:event_btnAddHospitalsActionPerformed

    private void btnSearchHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHospitalsActionPerformed
        // TODO add your handling code here:
        SearchHospitalPanel searchHospitalPanel = new SearchHospitalPanel(hospitalList, "Community Panel");
        splitPane.setBottomComponent(searchHospitalPanel);
    }//GEN-LAST:event_btnSearchHospitalsActionPerformed

    private void btnViewHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHospitalsActionPerformed
        // TODO add your handling code here:
        ViewHospitalPanel viewHospitalPanel = new ViewHospitalPanel(hospitalList);
        splitPane.setBottomComponent(viewHospitalPanel);
    }//GEN-LAST:event_btnViewHospitalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEncounter;
    private javax.swing.JButton btnAddHospitals;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnSearchHospitals;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JButton btnViewHospitals;
    private javax.swing.JButton btnViewPatient;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
