/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Login;
import model.LoginClass;

/**
 *
 * @author amretasrerengarajan
 */
public class ViewAdminDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewAdminDetails
     */
    LoginClass loginList;

    public ViewAdminDetails(LoginClass LoginList) {
        initComponents();

        this.loginList = LoginList;
        lblWarningUsername.setVisible(false);
        txtUpdatePassword.setText("");

        populateTable();
    }

    public void populateTable() {
        DefaultTableModel adminsTable = (DefaultTableModel) tblViewAdmins.getModel();
        adminsTable.setRowCount(0);
        for (Login login : loginList.getLoginList()) {
            Object[] row = new Object[2];
            row[0] = login;
            row[1] = login.getUserType();

            adminsTable.addRow(row);
        }
    }

    public void populateSearchResult(Login searchResult) {
        DefaultTableModel adminsTable = (DefaultTableModel) tblViewAdmins.getModel();
        adminsTable.setRowCount(0);

        Object[] row = new Object[2];
        row[0] = searchResult;
        row[1] = searchResult.getUserType();

        adminsTable.addRow(row);

    }

    public void populateWithSearchList(ArrayList<Login> searchUsers) {
        DefaultTableModel adminsTable = (DefaultTableModel) tblViewAdmins.getModel();
        adminsTable.setRowCount(0);
        for (Login login : searchUsers) {
            Object[] row = new Object[2];
            row[0] = login;
            row[1] = login.getUserType();

            adminsTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSearchType = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewAdmins = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        rdBtnUserName = new javax.swing.JRadioButton();
        rdBtnUserType = new javax.swing.JRadioButton();
        txtSearchField = new javax.swing.JTextField();
        btnSearchButton = new javax.swing.JButton();
        lblUpdateUserName = new javax.swing.JLabel();
        lblUpdatePassword = new javax.swing.JLabel();
        txtUpdateUserName = new javax.swing.JTextField();
        txtUpdatePassword = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblWarningUsername = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LIST OF ADMINS");

        tblViewAdmins.setBackground(new java.awt.Color(255, 0, 204));
        tblViewAdmins.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        tblViewAdmins.setForeground(new java.awt.Color(0, 255, 204));
        tblViewAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User Name", "User Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewAdmins);

        lblSearch.setForeground(new java.awt.Color(255, 0, 153));
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("Search By:");

        btnGrpSearchType.add(rdBtnUserName);
        rdBtnUserName.setText("User Name");
        rdBtnUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnUserNameActionPerformed(evt);
            }
        });

        btnGrpSearchType.add(rdBtnUserType);
        rdBtnUserType.setText("User Type");
        rdBtnUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnUserTypeActionPerformed(evt);
            }
        });

        btnSearchButton.setBackground(new java.awt.Color(204, 255, 204));
        btnSearchButton.setForeground(new java.awt.Color(0, 204, 0));
        btnSearchButton.setText("Search");
        btnSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchButtonActionPerformed(evt);
            }
        });

        lblUpdateUserName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblUpdateUserName.setForeground(new java.awt.Color(255, 0, 153));
        lblUpdateUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateUserName.setText("User Name:");

        lblUpdatePassword.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblUpdatePassword.setForeground(new java.awt.Color(255, 0, 153));
        lblUpdatePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdatePassword.setText("Password:");

        txtUpdateUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUpdateUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUpdateUserNameFocusLost(evt);
            }
        });

        txtUpdatePassword.setText("jPasswordField1");

        btnUpdate.setBackground(new java.awt.Color(204, 255, 204));
        btnUpdate.setForeground(new java.awt.Color(0, 204, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 255, 204));
        btnDelete.setForeground(new java.awt.Color(0, 204, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Password");

        lblWarningUsername.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarningUsername.setText("Cannot Edit");

        btnSave.setBackground(new java.awt.Color(204, 255, 204));
        btnSave.setForeground(new java.awt.Color(0, 204, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdBtnUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(rdBtnUserType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearchButton)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(147, 147, 147))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUpdatePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUpdateUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUpdateUserName)
                                    .addComponent(txtUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblWarningUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(rdBtnUserName)
                    .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdBtnUserType)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateUserName)
                    .addComponent(txtUpdateUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarningUsername))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdatePassword)
                    .addComponent(txtUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtnUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnUserNameActionPerformed
        // TODO add your handling code here:
        rdBtnUserName.setActionCommand("User Name");
    }//GEN-LAST:event_rdBtnUserNameActionPerformed

    private void rdBtnUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnUserTypeActionPerformed
        // TODO add your handling code here:
        rdBtnUserType.setActionCommand("User Type");
    }//GEN-LAST:event_rdBtnUserTypeActionPerformed

    private void btnSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchButtonActionPerformed
        // TODO add your handling code here:
        String searchText = txtSearchField.getText();
        Login searchResult = new Login();
        ArrayList<Login> serachResultList = new ArrayList<Login>();
        if (txtSearchField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "This field cannot be empty");
        } else {
            if (btnGrpSearchType.getSelection().getActionCommand().equals("User Name")) {
                searchResult = loginList.searchWithUserName(searchText);
                populateSearchResult(searchResult);
            } else if (btnGrpSearchType.getSelection().getActionCommand().equals("User Type")) {
                serachResultList = loginList.searchWithUserType(searchText);
                populateWithSearchList(serachResultList);
            } else {
                JOptionPane.showMessageDialog(this, "No Search Results Found");
            }
        }
    }//GEN-LAST:event_btnSearchButtonActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int adminInd = tblViewAdmins.getSelectedRow();
        
        if(adminInd < 0 ) {
            //if there is no row selected then a dialog is displayed
            JOptionPane.showMessageDialog(this, "Select the Hospital to be Updated.");
            return;
        }
        
        DefaultTableModel adminsTable = (DefaultTableModel) tblViewAdmins.getModel();
        
        Login selectedAdmin = (Login) adminsTable.getValueAt(adminInd, 0);
        
        txtUpdateUserName.setText(selectedAdmin.getUserName());
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtUpdateUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpdateUserNameFocusGained
        // TODO add your handling code here:
        lblWarningUsername.setVisible(true);
    }//GEN-LAST:event_txtUpdateUserNameFocusGained

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int adminInd = tblViewAdmins.getSelectedRow();
        
        if(adminInd < 0 ) {
            //if there is no row selected then a dialog is displayed
            JOptionPane.showMessageDialog(this, "Select the Hospital to be Updated.");
            return;
        }
        
        DefaultTableModel adminsTable = (DefaultTableModel) tblViewAdmins.getModel();
        
        Login selectedAdmin = (Login) adminsTable.getValueAt(adminInd, 0);
        
        loginList.deleteUser(selectedAdmin);
        
        JOptionPane.showMessageDialog(this, "Deleted the admin");
        
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int adminInd = tblViewAdmins.getSelectedRow();
        
        if(adminInd < 0 ) {
            //if there is no row selected then a dialog is displayed
            JOptionPane.showMessageDialog(this, "Select the Hospital to be Updated.");
            return;
        }
        
        DefaultTableModel adminsTable = (DefaultTableModel) tblViewAdmins.getModel();
        
        Login selectedAdmin = (Login) adminsTable.getValueAt(adminInd, 0);
        
        Login updatedPassword = loginList.updateUserInfo(selectedAdmin, adminInd);
        
        updatedPassword.setPassword(txtUpdatePassword.getText());
        
        JOptionPane.showMessageDialog(this, "Updated Password");
        txtUpdateUserName.setText("");
        txtUpdatePassword.setText("");
        
        populateTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtUpdateUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUpdateUserNameFocusLost
        // TODO add your handling code here:
        lblWarningUsername.setVisible(false);
    }//GEN-LAST:event_txtUpdateUserNameFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup btnGrpSearchType;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchButton;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdatePassword;
    private javax.swing.JLabel lblUpdateUserName;
    private javax.swing.JLabel lblWarningUsername;
    private javax.swing.JRadioButton rdBtnUserName;
    private javax.swing.JRadioButton rdBtnUserType;
    private javax.swing.JTable tblViewAdmins;
    private javax.swing.JTextField txtSearchField;
    private javax.swing.JPasswordField txtUpdatePassword;
    private javax.swing.JTextField txtUpdateUserName;
    // End of variables declaration//GEN-END:variables
}
