/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.PatientRecord;
import model.PatientRecordList;
import model.Person;
import model.PersonList;

/**
 *
 * @author amretasrerengarajan
 */
public class ViewPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientPanel
     */
    PatientRecord patientRecord;
    PatientRecordList patientList;
    PersonList personList;

    boolean isSysPresValid;
    boolean isDiaPresValid;
    boolean isDateValid;
    boolean isBreathingRateValid;
    boolean isHeartBeatValid;
    boolean isTemperatureValid;

    long patientID;
    String patientName;
    int patientSysPressure;
    int patientDiaPressure;
    int patientBreathing;
    int patientHeartRate;
    float patientTemperature;
    String patientEncounterDateTaken;

    public ViewPatientPanel(PatientRecordList patientList, PatientRecord patientRecord, PersonList personList) {
        initComponents();

        this.patientList = patientList;
        this.patientRecord = patientRecord;
        this.personList = personList;

        lblWarningBreathing.setVisible(false);
        lblWarningDate.setVisible(false);
        lblWarningDiaPressure.setVisible(false);
        lblWarningHeartBeat.setVisible(false);
        lblWarningSysPressure.setVisible(false);
        lblWarningTemperature.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        btnSearchPatient = new javax.swing.JButton();
        lblSearchType = new javax.swing.JLabel();
        rdBtnPatientId = new javax.swing.JRadioButton();
        rdBtnPatientName = new javax.swing.JRadioButton();
        lblSearchBox = new javax.swing.JLabel();
        txtSearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewEncounter = new javax.swing.JTable();
        lblPatientID = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        btnUpdateEncounter = new javax.swing.JButton();
        btnDeleteEncounter = new javax.swing.JButton();
        lblSysPressure = new javax.swing.JLabel();
        txtSysPressure = new javax.swing.JTextField();
        txtDiaPressure = new javax.swing.JTextField();
        lblDiaPressure = new javax.swing.JLabel();
        lblBreathing = new javax.swing.JLabel();
        txtBreathing = new javax.swing.JTextField();
        lblHeartBeat = new javax.swing.JLabel();
        txtHeartBeat = new javax.swing.JTextField();
        txtTemperature = new javax.swing.JTextField();
        lblTemperature = new javax.swing.JLabel();
        lblDateTaken = new javax.swing.JLabel();
        txtDateTaken = new javax.swing.JTextField();
        lblWarningDate = new javax.swing.JLabel();
        lblWarningTemperature = new javax.swing.JLabel();
        lblWarningHeartBeat = new javax.swing.JLabel();
        lblWarningBreathing = new javax.swing.JLabel();
        lblWarningDiaPressure = new javax.swing.JLabel();
        lblWarningSysPressure = new javax.swing.JLabel();
        btnSaveVitals = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 204));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Patient Vital History");

        btnSearchPatient.setText("Search Patient");
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });

        lblSearchType.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSearchType.setForeground(new java.awt.Color(255, 0, 204));
        lblSearchType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchType.setText("Search Patient By:");

        buttonGroup1.add(rdBtnPatientId);
        rdBtnPatientId.setText("Patient Id");
        rdBtnPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnPatientIdActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdBtnPatientName);
        rdBtnPatientName.setText("Patient Name");
        rdBtnPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnPatientNameActionPerformed(evt);
            }
        });

        lblSearchBox.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSearchBox.setForeground(new java.awt.Color(255, 0, 204));
        lblSearchBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchBox.setText("Search");

        tblViewEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date Taken", "Systolic Pressure", "Diastolic Pressure", "Breating Rate", "Heart Beat Rate", "Body Temperature"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblViewEncounter);

        lblPatientID.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblPatientID.setForeground(new java.awt.Color(255, 0, 204));
        lblPatientID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientID.setText("Patient ID:");

        lblPatientName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(255, 0, 204));
        lblPatientName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientName.setText("Patient Name:");

        btnUpdateEncounter.setText("Update Vital");
        btnUpdateEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEncounterActionPerformed(evt);
            }
        });

        btnDeleteEncounter.setText("Delete Vital");
        btnDeleteEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEncounterActionPerformed(evt);
            }
        });

        lblSysPressure.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSysPressure.setForeground(new java.awt.Color(255, 0, 204));
        lblSysPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSysPressure.setText("Systoic Pressure:");

        txtSysPressure.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSysPressureFocusLost(evt);
            }
        });

        txtDiaPressure.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaPressureFocusLost(evt);
            }
        });

        lblDiaPressure.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDiaPressure.setForeground(new java.awt.Color(255, 0, 204));
        lblDiaPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiaPressure.setText("Diastolic Pressure:");

        lblBreathing.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblBreathing.setForeground(new java.awt.Color(255, 0, 204));
        lblBreathing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBreathing.setText("Breathing");

        txtBreathing.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBreathingFocusLost(evt);
            }
        });

        lblHeartBeat.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblHeartBeat.setForeground(new java.awt.Color(255, 0, 204));
        lblHeartBeat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeartBeat.setText("Heart Beats:");

        txtHeartBeat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHeartBeatFocusLost(evt);
            }
        });

        txtTemperature.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTemperatureFocusLost(evt);
            }
        });

        lblTemperature.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTemperature.setForeground(new java.awt.Color(255, 0, 204));
        lblTemperature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTemperature.setText("Temperature:");

        lblDateTaken.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDateTaken.setForeground(new java.awt.Color(255, 0, 204));
        lblDateTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDateTaken.setText("Date Taken: ");

        txtDateTaken.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateTakenFocusLost(evt);
            }
        });
        txtDateTaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateTakenActionPerformed(evt);
            }
        });

        lblWarningDate.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningDate.setText("Invalid Date!");

        lblWarningTemperature.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningTemperature.setText("Invalid!");

        lblWarningHeartBeat.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningHeartBeat.setText("Invalid!");

        lblWarningBreathing.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningBreathing.setText("Invalid!");

        lblWarningDiaPressure.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningDiaPressure.setText("Invalid!");

        lblWarningSysPressure.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningSysPressure.setText("Invalid!");

        btnSaveVitals.setText("Save Vitals");
        btnSaveVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveVitalsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Vitals ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnUpdateEncounter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteEncounter)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPatientName)
                    .addComponent(lblPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSysPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiaPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBreathing, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHeartBeat, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblWarningHeartBeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblWarningBreathing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblWarningDiaPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblWarningSysPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWarningDate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblWarningTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblTemperature, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHeartBeat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBreathing, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDiaPressure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSysPressure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDateTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveVitals)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSearchBox)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(rdBtnPatientId)
                                .addGap(72, 72, 72)
                                .addComponent(rdBtnPatientName)))
                        .addGap(48, 48, 48)
                        .addComponent(btnSearchPatient)
                        .addGap(30, 30, 30))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblPatientID, lblPatientName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblSearchBox, lblSearchType});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteEncounter, btnSaveVitals, btnUpdateEncounter});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchType)
                    .addComponent(rdBtnPatientId)
                    .addComponent(rdBtnPatientName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchBox)
                    .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchPatient))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateEncounter)
                    .addComponent(btnDeleteEncounter))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSysPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSysPressure)
                    .addComponent(lblWarningSysPressure))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiaPressure)
                    .addComponent(lblWarningDiaPressure))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBreathing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBreathing)
                    .addComponent(lblWarningBreathing)
                    .addComponent(btnSaveVitals))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeartBeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeartBeat)
                    .addComponent(lblWarningHeartBeat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemperature)
                    .addComponent(lblWarningTemperature))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateTaken)
                    .addComponent(txtDateTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWarningDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addTableWithVitals() {
        DefaultTableModel encounterData = (DefaultTableModel) tblViewEncounter.getModel();

        encounterData.setRowCount(0);

        patientID = Long.parseLong(txtPatientID.getText());
        patientName = txtPatientName.getText();

        PatientRecord patientVitals = patientList.getPersonDetailsWithPatientId(patientID);

        for (Encounter encounter : patientVitals.getEncounterList()) {

            Object[] row = new Object[6];

            row[0] = encounter;
            row[1] = encounter.getSystolicPressure();
            row[2] = encounter.getDiastolicPressure();
            row[3] = encounter.getBreathing();
            row[4] = encounter.getBeats();
            row[5] = encounter.getTemperature();

            encounterData.addRow(row);
        }

    }

    public int checkSystolicPressure(String sysPressure) {
        String regex = "\\d{3}";
        int result;
        isSysPresValid = sysPressure.matches(regex);
        if (sysPressure.isEmpty()) {
            result = 0;
        } else {
            result = Integer.parseInt(sysPressure);
        }
        if (isSysPresValid && (result >= 120 || result <= 140)) {
            return result;
        } else {
            result = 0;
            return result;
        }
    }

    public int checkDiastolicPressure(String diaPressure) {
        String regex = "\\d{2}";
        int result;
        isDiaPresValid = diaPressure.matches(regex);
        if (diaPressure.isEmpty()) {
            result = 0;
        } else {
            result = Integer.parseInt(diaPressure);
        }
        if (isDiaPresValid && (result >= 80 || result <= 89)) {
            return result;
        } else {
            result = 0;
            return result;
        }
    }

    public int checkBreathing(String breathingRate) {
        String regex = "\\d{2}";
        int result;
        isBreathingRateValid = breathingRate.matches(regex);
        if (isBreathingRateValid && !breathingRate.isEmpty()) {
            result = Integer.parseInt(breathingRate);
        } else {
            result = 0;
        }
        return result;
    }

    public int checkHeartBeat(String heartBeat) {
        String regex = "\\d{2}";
        int result;
        isHeartBeatValid = heartBeat.matches(regex);
        if (isHeartBeatValid && !heartBeat.isEmpty()) {
            result = Integer.parseInt(heartBeat);
        } else {
            result = 0;
        }
        return result;
    }

    public float checkTemperature(String temperature) {
        String regex = "[+-]?([0-9]*[.])?[0-9]+";
        float result;
        isTemperatureValid = temperature.matches(regex);
        if (isTemperatureValid && !temperature.isEmpty()) {
            result = Float.parseFloat(temperature);
        } else {
            result = 0.0F;
        }
        return result;
    }

    public String checkDateTaken(String dateTaken) {
        String regex = "^[0-3]?[0-9]/[0-3]?[0-9]/(?:[0-9]{2})?[0-9]{2}$";
        //Creating a pattern object
        Pattern pattern = Pattern.compile(regex);
        //Matching the compiled pattern in the String
        Matcher matcher = pattern.matcher(dateTaken);
        isDateValid = matcher.matches();
        if (isDateValid) {
            return dateTaken;
        } else {
            return "";
        }
    }

    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
        // TODO add your handling code here:
        boolean searchResult;
        Person searchPersonResult = new Person();
        if (buttonGroup1.getSelection().getActionCommand().equals("Patient ID")) {
            searchResult = patientList.searchPersonByPatientID(Long.parseLong(txtSearchField.getText()));
            if (searchResult) {
                searchPersonResult = patientList.getPersonDetailsWithPatientId(Long.parseLong(txtSearchField.getText()));
                txtPatientID.setText(String.valueOf(searchPersonResult.getPersonId()));
                txtPatientName.setText(searchPersonResult.getPersonName());
                addTableWithVitals();
                txtSearchField.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "No patient records found. Create Patient Records First");
                txtSearchField.setText("");
            }
        } else if (buttonGroup1.getSelection().getActionCommand().equals("Patient Name")) {
            searchResult = patientList.searchPersonByPatientName(txtSearchField.getText());
            if (searchResult) {
                searchPersonResult = patientList.getPersonDetailsWithPatientName(txtSearchField.getText());
                txtPatientID.setText(String.valueOf(searchPersonResult.getPersonId()));
                txtPatientName.setText(searchPersonResult.getPersonName());
                addTableWithVitals();
                txtSearchField.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "No patient records found. Create Patient Records First");
                txtSearchField.setText("");
            }
        }
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void rdBtnPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnPatientIdActionPerformed
        // TODO add your handling code here:
        rdBtnPatientId.setActionCommand("Patient ID");
    }//GEN-LAST:event_rdBtnPatientIdActionPerformed

    private void rdBtnPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnPatientNameActionPerformed
        // TODO add your handling code here:
        rdBtnPatientName.setActionCommand("Patient Name");
    }//GEN-LAST:event_rdBtnPatientNameActionPerformed

    private void txtSysPressureFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSysPressureFocusLost
        // TODO add your handling code here:
        patientSysPressure = checkSystolicPressure(txtSysPressure.getText());
        if (txtSysPressure.getText().isEmpty()) {
            lblWarningSysPressure.setVisible(false);
        } else {
            if (patientSysPressure == 0) {
                txtSysPressure.setText("");
                lblWarningSysPressure.setVisible(true);
            } else {
                lblWarningSysPressure.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtSysPressureFocusLost

    private void txtDiaPressureFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaPressureFocusLost
        // TODO add your handling code here:
        patientDiaPressure = checkDiastolicPressure(txtDiaPressure.getText());
        if (txtDiaPressure.getText().isEmpty()) {
            lblWarningDiaPressure.setVisible(false);
        } else {
            if (patientDiaPressure == 0) {
                txtPatientID.setText("");
                lblWarningDiaPressure.setVisible(true);
            } else {
                lblWarningDiaPressure.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtDiaPressureFocusLost

    private void txtBreathingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBreathingFocusLost
        // TODO add your handling code here:
        patientBreathing = checkBreathing(txtBreathing.getText());
        if (txtBreathing.getText().isEmpty()) {
            lblWarningBreathing.setVisible(false);
        } else {
            if (patientBreathing == 0) {
                txtBreathing.setText("");
                lblWarningBreathing.setVisible(true);
            } else {
                lblWarningBreathing.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtBreathingFocusLost

    private void txtHeartBeatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHeartBeatFocusLost
        // TODO add your handling code here:
        patientHeartRate = checkHeartBeat(txtHeartBeat.getText());
        if (txtHeartBeat.getText().isEmpty()) {
            lblWarningHeartBeat.setVisible(false);
        } else {
            if (patientHeartRate == 0) {
                txtHeartBeat.setText("");
                lblWarningHeartBeat.setVisible(true);
            } else {
                lblWarningHeartBeat.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtHeartBeatFocusLost

    private void txtTemperatureFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTemperatureFocusLost
        // TODO add your handling code here:
        patientTemperature = checkTemperature(txtTemperature.getText());
        if (txtTemperature.getText().isEmpty()) {
            lblWarningTemperature.setVisible(false);
        } else {
            if (patientTemperature == 0.0) {
                txtTemperature.setText(String.valueOf(patientTemperature));
                lblWarningTemperature.setVisible(true);
            } else {
                lblWarningTemperature.setVisible(false);
            }
        }
    }//GEN-LAST:event_txtTemperatureFocusLost

    private void txtDateTakenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateTakenFocusLost
        // TODO add your handling code here:
        String typedEncounterDate = txtDateTaken.getText();
        patientEncounterDateTaken = checkDateTaken(typedEncounterDate);
        if (typedEncounterDate.isEmpty()) {
            lblWarningDate.setVisible(false);
        } else {
            if (isDateValid) {
                lblWarningDate.setVisible(false);
            } else {
                //                txtDateTaken.setText("");
                lblWarningDate.setVisible(true);
            }
        }
    }//GEN-LAST:event_txtDateTakenFocusLost

    private void txtDateTakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateTakenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateTakenActionPerformed

    private void btnUpdateEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEncounterActionPerformed
        // TODO add your handling code here:

        int encounterInd = tblViewEncounter.getSelectedRow();

        if (encounterInd < 0) {
            //if there is no row selected then a dialog is displayed
            JOptionPane.showMessageDialog(this, "Select the Record to be Updated.");
            return;
        }

        DefaultTableModel encounterTable = (DefaultTableModel) tblViewEncounter.getModel();

        Encounter selectedEncounter = (Encounter) encounterTable.getValueAt(encounterInd, 0);

        txtDateTaken.setText(selectedEncounter.getDateTaken());
        txtBreathing.setText(String.valueOf(selectedEncounter.getBreathing()));
        txtDiaPressure.setText(String.valueOf(selectedEncounter.getDiastolicPressure()));
        txtHeartBeat.setText(String.valueOf(selectedEncounter.getBeats()));
        txtSysPressure.setText(String.valueOf(selectedEncounter.getSystolicPressure()));
        txtTemperature.setText(String.valueOf(selectedEncounter.getTemperature()));

    }//GEN-LAST:event_btnUpdateEncounterActionPerformed

    private void btnSaveVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveVitalsActionPerformed
        // TODO add your handling code here:

        int encounterInd = tblViewEncounter.getSelectedRow();

        if (encounterInd < 0) {
            //if there is no row selected then a dialog is displayed
            JOptionPane.showMessageDialog(this, "Select the Hospital to be Updated.");
            return;
        }

        DefaultTableModel encounterTable = (DefaultTableModel) tblViewEncounter.getModel();

        Encounter selectedEnc = (Encounter) encounterTable.getValueAt(encounterInd, 0);

        String dateTaken = txtDateTaken.getText();
        int sysPressure = Integer.parseInt(txtSysPressure.getText());
        int diaPressure = Integer.parseInt(txtDiaPressure.getText());
        int breathing = Integer.parseInt(txtBreathing.getText());
        int heartRate = Integer.parseInt(txtHeartBeat.getText());
        float temperature = Float.parseFloat(txtTemperature.getText());
        
        PatientRecord patient = patientList.getPersonDetailsWithPatientId(patientID);
        Encounter updatedEncounter = patient.updateEncounter(selectedEnc, encounterInd);

        updatedEncounter.setDateTaken(dateTaken);
        updatedEncounter.setSystolicPressure(sysPressure);
        updatedEncounter.setDiastolicPressure(diaPressure);
        updatedEncounter.setBeats(heartRate);
        updatedEncounter.setBreathing(breathing);
        updatedEncounter.setTemperature(temperature);

        JOptionPane.showMessageDialog(this, "Updated Details");

        txtBreathing.setText("");
        txtDateTaken.setText("");
        txtDiaPressure.setText("");
        txtHeartBeat.setText("");
        txtSysPressure.setText("");
        txtTemperature.setText("");
        
        addTableWithVitals();
    }//GEN-LAST:event_btnSaveVitalsActionPerformed

    private void btnDeleteEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEncounterActionPerformed
        // TODO add your handling code here:
        int encounterInd = tblViewEncounter.getSelectedRow();

        if (encounterInd < 0) {
            //if there is no row selected then a dialog is displayed
            JOptionPane.showMessageDialog(this, "Select the Record to be Updated.");
            return;
        }

        DefaultTableModel encounterTable = (DefaultTableModel) tblViewEncounter.getModel();

        Encounter selectedEncounter = (Encounter) encounterTable.getValueAt(encounterInd, 0);
        
        PatientRecord patient = patientList.getPersonDetailsWithPatientId(patientID);
        
        patient.removeEncounter(selectedEncounter);
        
        JOptionPane.showMessageDialog(this, "Deleted the Details");
        
        addTableWithVitals();
    }//GEN-LAST:event_btnDeleteEncounterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteEncounter;
    private javax.swing.JButton btnSaveVitals;
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JButton btnUpdateEncounter;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBreathing;
    private javax.swing.JLabel lblDateTaken;
    private javax.swing.JLabel lblDiaPressure;
    private javax.swing.JLabel lblHeartBeat;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblSearchBox;
    private javax.swing.JLabel lblSearchType;
    private javax.swing.JLabel lblSysPressure;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWarningBreathing;
    private javax.swing.JLabel lblWarningDate;
    private javax.swing.JLabel lblWarningDiaPressure;
    private javax.swing.JLabel lblWarningHeartBeat;
    private javax.swing.JLabel lblWarningSysPressure;
    private javax.swing.JLabel lblWarningTemperature;
    private javax.swing.JRadioButton rdBtnPatientId;
    private javax.swing.JRadioButton rdBtnPatientName;
    private javax.swing.JTable tblViewEncounter;
    private javax.swing.JTextField txtBreathing;
    private javax.swing.JTextField txtDateTaken;
    private javax.swing.JTextField txtDiaPressure;
    private javax.swing.JTextField txtHeartBeat;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtSearchField;
    private javax.swing.JTextField txtSysPressure;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
