/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.EmpDetail;
import model.EmpDetailsList;

//import model.EmpDetailsList;

/**
 *
 * @author amretasrerengarajan
 */
public class TableJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TableJPanel
     */
//    EmpDetail empDet;
    EmpDetailsList empList;
    
    public TableJPanel(EmpDetail empDet) {
        initComponents();
//        this.empDet = empDet;
        //creating the table model using DefaultTableModel
        searchResultTable(empDet);
    }
    
//    public TableJPanel(EmpDetailsList empDetList) {
//        initComponents();
//        this.empDet = empDet;
//        creating the table model using DefaultTableModel
//        searchResultTableList(empDetList);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchResults = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        tblSearchResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Joining Date", "Skills", "Deployed Team", "Position", "Email ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSearchResults);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Search Results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(778, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void searchResultTable(EmpDetail empDet) {
        DefaultTableModel empTable = (DefaultTableModel) tblSearchResults.getModel();
        empTable.setRowCount(0);


        Object[] row = new Object[7];
        row[0] = empDet.getEmpId();
        row[1] = empDet.getName();
        row[2] = empDet.getStartDate();
        row[3] = empDet.getLevel();
        row[4] = empDet.getTeamInfo();
        row[5] = empDet.getPositionTitle();
        row[6] = empDet.getEmailId();
        
        empTable.addRow(row);
       
    }
    
//     private void searchResultTableList(EmpDetailsList empDetList) {
//        DefaultTableModel empTable = (DefaultTableModel) tblSearchResults.getModel();
//        empTable.setRowCount(0);
//
//        for(EmpDetail empDetail: empList.getEmpList()) {   
//            //creating the row array and adding the required information in the respective column(index)
//            Object[] row = new Object[7];
//            row[0] = empDetail.getEmpId();
//            row[1] = empDetail.getName();
//            row[2] = empDetail.getStartDate();
//            row[3] = empDetail.getLevel();
//            row[4] = empDetail.getTeamInfo();
//            row[5] = empDetail.getPositionTitle();
//            row[6] = empDetail.getEmailId();
//            
//            //adding the row array to the table
//            empTable.addRow(row);
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblSearchResults;
    // End of variables declaration//GEN-END:variables
}
